Repository joonas-yoon/boj-extended, pull requests merged in 2022-08, with the labels that each got.

#100 version: 1.8.2
  .eslintrc
  README.md
  UPDATENOTE.md
  build.sh
  css/common.css
  css/theme-dark.css
  css/theme-rigel.css
  dist/manifest.json
  js/constants.js
  js/db.js
  js/features/board.js
  js/features/global.js
  js/features/group.js
  js/features/problem.js
  js/features/search.js
  js/features/setting.js
  js/features/status/all.js
  js/features/status/rte.js
  js/features/theme.js
  js/features/user.js
  js/features/vs.js
  js/features/wide.js
  js/preload.js
  js/theme.js
  js/utils/config.js
  js/utils/helpers.js
  js/utils/index.js
  manifest.json
  options/jquery-3.6.0.min.js
  options/option-timer.html
  options/option-timer.js
  options/option.html
  options/option.js
  util/bot.py
Labels: ✨ new feature, 🚧 deploy

#102 update bot
  .github/workflows/bot.yml
  db.json
  util/bot.py
Labels: 🚧 deploy

#101 fix: changes specific header in request to xhr (#97)
  .gitignore
  manifest.json
  rules.json
Labels: 🎈 good first, 👍 enhancement, priority: 4, 🥚 awaiting review

#105 version: 1.8.3.1
  UPDATENOTE.md
  css/common.css
  css/user.css
  js/constants.js
  js/features/global.js
  js/features/status/all.js
  js/features/status/rte.js
  js/features/theme.js
  manifest.json
Labels: 🐛 bug, ✨ new feature, 👍 enhancement

#108 version: 1.8.4
  UPDATENOTE.md
  css/common.css
  css/status.css
  css/theme-rigel.css
  js/constants.js
  js/features/global.js
  js/features/status/rte.js
  js/features/theme.js
  js/features/vs.js
  js/utils/helpers.js
  js/utils/index.js
  manifest.json
  options/option.html
  options/option.js
Labels: 🚧 deploy
